# Makefile for LTAL 

helf = ../../bin/helf +RTS -sstderr -RTS
helf-prof = ../../bin/helf-prof +RTS -p -h -sstderr -RTS
big = w32_sig_semant.elf

default : 	
	$(helf) $(big)

prof : 	
	$(helf-prof) $(big)

# EOF
